/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Helper.Auth;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.mail.PasswordAuthentication;
import java.util.Properties;
import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.mail.*;
import javax.mail.internet.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author huyhoai
 */
public class GuiBaoCaoTK extends javax.swing.JFrame {

    File file = null;
    String from = null;
    String to = null;
    String host = null;
    String subject = null;
    String body = null;
    MimeMultipart multipart;
    FileDataSource fds;
    MimeBodyPart filePart;
    String nv = " ";
    String tt = " ";
    String shd = " ";
    String ssp = " ";
    String sl = " ";

    /**
     * Creates new form GuiBaoCaoTK
     */
    public GuiBaoCaoTK() {
        initComponents();
        this.setLocationRelativeTo(null);
        checkThongtin();
        txtgmailnv.setText("hoaidao17102003@gmail.com");
        txtpassnv.setText("00000000000");
        txtgmailquanly.setText("hoaidthps21446@fpt.edu.vn");
        txtsubject.setText("báo cáo");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }

    public void checkThongtin() {
        ThongKeForm tkf = new ThongKeForm();
            if (tkf.ListTKHD.size() < 0) {
                nv = "0";
                tt = "0";
                shd = "0";
                ssp = "0";
                sl = "0";
                taconten.setText("Ngày: " + new SimpleDateFormat("dd-MM-yyyy").format(new Date()) + "\n" + "Nhân Viên: " + nv + "\n"
                        + "Tổng tiền hôm nay: " + tt + " VND" + "\n"
                        + "Số hóa đơn: " + shd + "\n"
                        + "Số khách hàng: " + ssp + "\n"
                        + "Số sản phẩm: " + sl);
            } else {
                if (!Auth.user.getTenNV().equalsIgnoreCase(" ")) {
                    nv = Auth.user.getTenNV();
                }
                for (int i = 0; i < tkf.ListTKHD.size(); i++) {
                    if ((tkf.ListTKHD.size()- 1)==i) {
                        tt = String.valueOf(tkf.ListTKHD.get(i).getTongtien());
                        shd = String.valueOf(tkf.ListTKHD.get(i).getMahd());
                        ssp = String.valueOf(tkf.ListTKHD.get(i).getMasp());
                        sl = String.valueOf(tkf.ListTKHD.get(i).getSoluong());
                        break;
                    }
                }
                taconten.setText("Ngày: " + new SimpleDateFormat("dd-MM-yyyy").format(new Date()) + "\n" + "Nhân Viên: " + nv + "\n"
                        + "Tổng tiền hôm nay: " + tt + "VND" + "\n"
                        + "Số hóa đơn: " + shd + "\n"
                        + "Số khách hàng: " + ssp + "\n"
                        + "Số sản phẩm: " + sl);
            }
    }

//    public void check() {
//        ThongKeForm tkf = new ThongKeForm();
//        if (String.valueOf(tkf.ListTKHD.get(0).getMahd()).equalsIgnoreCase("")) {
//            nv = "0";
//            tt = "0";
//            shd = "0";
//            ssp = "0";
//            sl = "0";
//            taconten.setText("Ngày: " + new SimpleDateFormat("dd-MM-yyyy").format(new Date()) + "\n" + "Nhân Viên: " + nv + "\n"
//                    + "Tổng tiền hôm nay: " + tt + "VND" + "\n"
//                    + "Số hóa đơn: " + shd + "\n"
//                    + "Số sản phẩm: " + ssp + "\n"
//                    + "Số lượng: " + sl);
//        } else {
//            taconten.setText("Ngày: " + new SimpleDateFormat("dd-MM-yyyy").format(new Date()) + "\n" + "Nhân Viên: " + nv + "\n"
//                    + "Tổng tiền hôm nay: " + tt + "VND" + "\n"
//                    + "Số hóa đơn: " + shd + "\n"
//                    + "Số sản phẩm: " + ssp + "\n"
//                    + "Số lượng: " + sl);
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtgmailnv = new javax.swing.JTextField();
        txtpassnv = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtgmailquanly = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taconten = new javax.swing.JTextArea();
        txtsubject = new javax.swing.JTextField();
        btnsend = new javax.swing.JButton();
        btnfile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Gửi Báo Cáo Thống Kê");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("NHÂN VIÊN"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Gmail Nhân Viên:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 34, -1, -1));
        jPanel1.add(txtgmailnv, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 31, 197, -1));
        jPanel1.add(txtpassnv, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 71, 197, -1));

        jLabel3.setText("Mật Khẩu Nhân Viên:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 74, -1, -1));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 390, 110));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("QUẢN LÝ"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(txtgmailquanly, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 37, 195, -1));

        jLabel4.setText("Gmail Quản Lý:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 40, -1, -1));

        jLabel5.setText("Subject:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 95, -1, -1));

        taconten.setColumns(20);
        taconten.setRows(5);
        jScrollPane1.setViewportView(taconten);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 127, 331, 167));
        jPanel2.add(txtsubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 92, 195, -1));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 390, 320));

        btnsend.setText("Send");
        btnsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendActionPerformed(evt);
            }
        });
        jPanel4.add(btnsend, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, -1, -1));

        btnfile.setText("File");
        btnfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfileActionPerformed(evt);
            }
        });
        jPanel4.add(btnfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfileActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        if (fc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            file = fc.getSelectedFile();
        }
    }//GEN-LAST:event_btnfileActionPerformed

    private void btnsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendActionPerformed
        // TODO add your handling code here:
        SendMail();
    }//GEN-LAST:event_btnsendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiBaoCaoTK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiBaoCaoTK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiBaoCaoTK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiBaoCaoTK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiBaoCaoTK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfile;
    private javax.swing.JButton btnsend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taconten;
    private javax.swing.JTextField txtgmailnv;
    private javax.swing.JTextField txtgmailquanly;
    private javax.swing.JPasswordField txtpassnv;
    private javax.swing.JTextField txtsubject;
    // End of variables declaration//GEN-END:variables

    public void SendMail() {

        from = txtgmailnv.getText();
        to = txtgmailquanly.getText();
        host = "localhost";
        subject = txtsubject.getText();
        body = taconten.getText();
        String cc = "hoaidthps21446@fpt.edu.vn,hhoai17102003@gmail.com";
//        String bcc = "hoaidthps21446@fpt.edu.vn,hhoai17102003@gmail.com";

        Properties p = new Properties();
        p.put("mail.smtp.auth", "true");
        p.put("mail.smtp.starttls.enable", "true");
        p.put("mail.smtp.host", "smtp.gmail.com");//chỉ ra máy chủ mail của google...smtp.gmail.com            
        p.put("mail.smtp.port", "587");//

        String password = "mghamlblbyxluxkd";
        String user = "hoaidao17102003@gmail.com";
        txtpassnv.setText(password);
        txtgmailnv.setText(user);
        Session s = Session.getDefaultInstance(p,
                new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(user, password);
            }
        });

        try {
            MimeMessage m = new MimeMessage(s);
            m.setFrom(from);
//            if (rdocc.isSelected()) {
//                m.setRecipients(Message.RecipientType.CC, InternetAddress.parse(to));
//            } else if (rdobcc.isSelected()) {
//                m.setRecipients(Message.RecipientType.BCC, InternetAddress.parse(to));
//            } else {
            m.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to));
//            }
            m.setSubject(subject);
//            m.setText(body);
            BodyPart MessageBodyPart = new MimeBodyPart();
            MessageBodyPart.setText(taconten.getText());
            Multipart multipart = new MimeMultipart();
            multipart.addBodyPart(MessageBodyPart);
            if (file != null) {
                BodyPart FileBodyPart = new MimeBodyPart();
                DataSource source = new FileDataSource(file);
                FileBodyPart.setDataHandler(new DataHandler(source));
                FileBodyPart.setFileName(file.getName());
                multipart.addBodyPart(FileBodyPart);
            }
            m.setContent(multipart);
            Transport.send(m);
            JOptionPane.showMessageDialog(this, "Đã gửi mail thành công", "Message", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (MessagingException e) {
            e.printStackTrace();
        }
    }

}
