/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI;

import java.sql.*;
import DAO.NhaPhanPhoiDAO;
import DAO.SanPhamDAO;
import ENTITY.NhaPhanPhoi;
import ENTITY.SanPham;
import Helper.Auth;
import Helper.XDate;
import Helper.XImage;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.Reader;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.BufferedWriter;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import net.glxn.qrgen.QRCode;
import net.glxn.qrgen.image.ImageType;

/**
 *
 * @author Admin
 */
public class SanPhamForm extends javax.swing.JInternalFrame {

    NhaPhanPhoiDAO daoNPP = new NhaPhanPhoiDAO();
    int row = -1;
    SanPhamDAO daoSP = new SanPhamDAO();
    DefaultTableModel modelSP = null;
    ArrayList<SanPham> listSP = null;
    DefaultTableModel modelNPP = null;
    ArrayList<NhaPhanPhoi> listNPP = null;

    /**
     * Creates new form SanPhamForm
     */
    public SanPhamForm() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        fillComBoBox();
        fillTableNhaPP();
        fillTableSP();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        fileChooserNPP = new javax.swing.JFileChooser();
        fileChooserSP = new javax.swing.JFileChooser();
        jLabel13 = new javax.swing.JLabel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        mniGiamGiaSP = new javax.swing.JMenuItem();
        lblQR = new javax.swing.JLabel();
        txtMaPP = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhaPhanPhoi = new javax.swing.JTable();
        txtNSXPP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaNPP = new javax.swing.JTextField();
        txtTenNhaPP = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lblHinhNPP = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFindNPP = new javax.swing.JTextField();
        btnFindPP = new javax.swing.JButton();
        btnFirstPP = new javax.swing.JButton();
        btnPrevPP = new javax.swing.JButton();
        btnNextPP = new javax.swing.JButton();
        btnLastPP = new javax.swing.JButton();
        pnlChucNangPP = new javax.swing.JPanel();
        btnThemPP = new javax.swing.JButton();
        btnUpdatePP = new javax.swing.JButton();
        btnDelPP = new javax.swing.JButton();
        btnClearPP = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDonGiaSP = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        cboLoai = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        txtSoLuongSP = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnThemSP = new javax.swing.JButton();
        btnUpdateSP = new javax.swing.JButton();
        btnDelSP = new javax.swing.JButton();
        btnClearSP = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtFindSP = new javax.swing.JTextField();
        btnFindSP = new javax.swing.JButton();
        btnFirstSP = new javax.swing.JButton();
        btnPrevSP = new javax.swing.JButton();
        btnNextSP = new javax.swing.JButton();
        btnLastSP = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        rdoConHang = new javax.swing.JRadioButton();
        rdoHetHang = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        lblHinhSP = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taMoTa = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        cboNhaPP = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnQR = new javax.swing.JButton();

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Mã phân phối:");

        mniGiamGiaSP.setText("Giảm giá từng sản phẩm");
        mniGiamGiaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGiamGiaSPActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mniGiamGiaSP);

        lblQR.setText("jLabel17");

        txtMaPP.setEditable(false);

        setPreferredSize(new java.awt.Dimension(990, 690));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ SẢN PHẨM");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(355, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 50));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblNhaPhanPhoi.setAutoCreateRowSorter(true);
        tblNhaPhanPhoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MÃ NHÀ PHÂN PHỐI", "TÊN NHÀ PHÂN PHỐI", "NƠI SẢN XUẤT", "HÌNH"
            }
        ));
        tblNhaPhanPhoi.setToolTipText("");
        tblNhaPhanPhoi.setGridColor(new java.awt.Color(255, 255, 255));
        tblNhaPhanPhoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblNhaPhanPhoiMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhaPhanPhoi);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 990, 290));
        jPanel1.add(txtNSXPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 190, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nơi sản xuất:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 140, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Mã nhà phân phối:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 140, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Tên nhà phân phối:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 140, 30));
        jPanel1.add(txtMaNPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 190, 30));
        jPanel1.add(txtTenNhaPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 190, 30));

        lblHinhNPP.setBackground(new java.awt.Color(255, 255, 255));
        lblHinhNPP.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblHinhNPP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHinhNPP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhNPPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblHinhNPP, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHinhNPP, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 160, 180));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Tìm kiếm:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 90, 30));

        txtFindNPP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFindNPPKeyPressed(evt);
            }
        });
        jPanel1.add(txtFindNPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 470, 30));

        btnFindPP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFindPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/search.png"))); // NOI18N
        btnFindPP.setText("Tìm");
        btnFindPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindPPActionPerformed(evt);
            }
        });
        jPanel1.add(btnFindPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 120, 40));

        btnFirstPP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFirstPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/first.png"))); // NOI18N
        btnFirstPP.setBorder(null);
        btnFirstPP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFirstPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstPPActionPerformed(evt);
            }
        });
        jPanel1.add(btnFirstPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 40, 40));

        btnPrevPP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPrevPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/prev.png"))); // NOI18N
        btnPrevPP.setBorder(null);
        btnPrevPP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrevPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevPPActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrevPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 40, 40));

        btnNextPP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNextPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/next.png"))); // NOI18N
        btnNextPP.setBorder(null);
        btnNextPP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNextPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextPPActionPerformed(evt);
            }
        });
        jPanel1.add(btnNextPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 260, 40, 40));

        btnLastPP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLastPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/last.png"))); // NOI18N
        btnLastPP.setBorder(null);
        btnLastPP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLastPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastPPActionPerformed(evt);
            }
        });
        jPanel1.add(btnLastPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 260, 40, 40));

        pnlChucNangPP.setBackground(new java.awt.Color(255, 255, 255));

        btnThemPP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThemPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/save.png"))); // NOI18N
        btnThemPP.setText("Thêm");
        btnThemPP.setBorder(null);
        btnThemPP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThemPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPPActionPerformed(evt);
            }
        });

        btnUpdatePP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdatePP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/update.png"))); // NOI18N
        btnUpdatePP.setText("Sửa");
        btnUpdatePP.setBorder(null);
        btnUpdatePP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdatePP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePPActionPerformed(evt);
            }
        });

        btnDelPP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDelPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Delete.png"))); // NOI18N
        btnDelPP.setText("Xóa");
        btnDelPP.setBorder(null);
        btnDelPP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelPPActionPerformed(evt);
            }
        });

        btnClearPP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClearPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/new.png"))); // NOI18N
        btnClearPP.setText("Mới");
        btnClearPP.setBorder(null);
        btnClearPP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearPPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlChucNangPPLayout = new javax.swing.GroupLayout(pnlChucNangPP);
        pnlChucNangPP.setLayout(pnlChucNangPPLayout);
        pnlChucNangPPLayout.setHorizontalGroup(
            pnlChucNangPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChucNangPPLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(pnlChucNangPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThemPP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdatePP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelPP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearPP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        pnlChucNangPPLayout.setVerticalGroup(
            pnlChucNangPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChucNangPPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemPP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnUpdatePP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnDelPP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnClearPP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(pnlChucNangPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 160, 220));

        jTabbedPane1.addTab("NHÀ PHÂN PHỐI", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Mô tả");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 80, 30));
        jPanel2.add(txtMaSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 180, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Tình trạng:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 100, 30));
        jPanel2.add(txtDonGiaSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 150, 30));

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ SẢN PHẨM", "TÊN SẢN PHẨM", "MÃ NHÀ PHÂN PHỐI", "TÊN NHÀ PHÂN PHỐI", "SỐ LƯỢNG", "ĐƠN GIÁ", "LOẠI", "MÔ TẢ", "HÌNH", "TÌNH TRẠNG"
            }
        ));
        tblSanPham.setComponentPopupMenu(jPopupMenu1);
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblSanPhamMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblSanPham);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 990, 260));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Tên sản phẩm:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, 30));

        cboLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn loại", "Laptop", "Tai nghe", "Chuột", "Bàn phím" }));
        jPanel2.add(cboLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 180, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Nhà phân phối:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Số lượng:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 30));
        jPanel2.add(txtTenSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 180, 30));
        jPanel2.add(txtSoLuongSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 180, 30));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnThemSP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThemSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/save.png"))); // NOI18N
        btnThemSP.setText("Thêm");
        btnThemSP.setBorder(null);
        btnThemSP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSPActionPerformed(evt);
            }
        });

        btnUpdateSP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdateSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/update.png"))); // NOI18N
        btnUpdateSP.setText("Sửa");
        btnUpdateSP.setBorder(null);
        btnUpdateSP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateSPActionPerformed(evt);
            }
        });

        btnDelSP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDelSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Delete.png"))); // NOI18N
        btnDelSP.setText("Xóa");
        btnDelSP.setBorder(null);
        btnDelSP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelSPActionPerformed(evt);
            }
        });

        btnClearSP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClearSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/new.png"))); // NOI18N
        btnClearSP.setText("Mới");
        btnClearSP.setBorder(null);
        btnClearSP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThemSP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateSP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelSP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearSP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemSP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnUpdateSP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnDelSP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnClearSP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 170, 220));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Tìm kiếm:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 90, 30));

        txtFindSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFindSPKeyPressed(evt);
            }
        });
        jPanel2.add(txtFindSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 470, 30));

        btnFindSP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFindSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/search.png"))); // NOI18N
        btnFindSP.setText("Tìm");
        btnFindSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindSPActionPerformed(evt);
            }
        });
        jPanel2.add(btnFindSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 120, 40));

        btnFirstSP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFirstSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/first.png"))); // NOI18N
        btnFirstSP.setBorder(null);
        btnFirstSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstSPActionPerformed(evt);
            }
        });
        jPanel2.add(btnFirstSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 40, 40));

        btnPrevSP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPrevSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/prev.png"))); // NOI18N
        btnPrevSP.setBorder(null);
        btnPrevSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevSPActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrevSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 40, 40));

        btnNextSP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNextSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/next.png"))); // NOI18N
        btnNextSP.setBorder(null);
        btnNextSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextSPActionPerformed(evt);
            }
        });
        jPanel2.add(btnNextSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 290, 40, 40));

        btnLastSP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLastSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/last.png"))); // NOI18N
        btnLastSP.setBorder(null);
        btnLastSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastSPActionPerformed(evt);
            }
        });
        jPanel2.add(btnLastSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 290, 40, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Mã sản phẩm:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Đơn giá:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 100, 30));

        buttonGroup1.add(rdoConHang);
        rdoConHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoConHang.setText("Còn hàng");
        jPanel2.add(rdoConHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        buttonGroup1.add(rdoHetHang);
        rdoHetHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoHetHang.setText("Hết hàng");
        rdoHetHang.setEnabled(false);
        jPanel2.add(rdoHetHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        lblHinhSP.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblHinhSP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHinhSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhSPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHinhSP, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHinhSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 170, 170));

        taMoTa.setColumns(20);
        taMoTa.setRows(5);
        jScrollPane3.setViewportView(taMoTa);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 230, 220));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Loại:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 100, 30));

        cboNhaPP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboNhaPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNhaPPActionPerformed(evt);
            }
        });
        jPanel2.add(cboNhaPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 180, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("VNĐ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 30, 30));

        btnQR.setText("QR");
        btnQR.setEnabled(false);
        btnQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQRActionPerformed(evt);
            }
        });
        jPanel2.add(btnQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 90, -1));

        jTabbedPane1.addTab("SẢN PHẨM", jPanel2);

        jPanel7.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 630));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1000, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblHinhSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhSPMouseClicked
        // TODO add your handling code here:
        this.selectImageSP();
    }//GEN-LAST:event_lblHinhSPMouseClicked

    private void btnLastSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastSPActionPerformed
        // TODO add your handling code here:
        this.LastSP();
    }//GEN-LAST:event_btnLastSPActionPerformed

    private void btnNextSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextSPActionPerformed
        // TODO add your handling code here:
        this.NextSP();
    }//GEN-LAST:event_btnNextSPActionPerformed

    private void btnPrevSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevSPActionPerformed
        // TODO add your handling code here:
        this.PrevSP();
    }//GEN-LAST:event_btnPrevSPActionPerformed

    private void btnFirstSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstSPActionPerformed
        // TODO add your handling code here:
        this.firstSP();
    }//GEN-LAST:event_btnFirstSPActionPerformed

    private void btnFindSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindSPActionPerformed
        // TODO add your handling code here:
        this.fillTableSP();
    }//GEN-LAST:event_btnFindSPActionPerformed

    private void btnClearSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearSPActionPerformed
        // TODO add your handling code here:
        this.clearSP();
    }//GEN-LAST:event_btnClearSPActionPerformed

    private void btnDelSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelSPActionPerformed
        // TODO add your handling code here:
        this.deleteSP();
        this.clearSP();
    }//GEN-LAST:event_btnDelSPActionPerformed

    private void btnUpdateSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSPActionPerformed
        // TODO add your handling code here:
        this.updateSP();
    }//GEN-LAST:event_btnUpdateSPActionPerformed

    private void btnThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSPActionPerformed
        // TODO add your handling code here:
        this.insertSP();
    }//GEN-LAST:event_btnThemSPActionPerformed

    private void tblSanPhamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMousePressed
        // TODO add your handling code here:
        this.row = tblSanPham.rowAtPoint(evt.getPoint());
        if (this.row >= 0) {
            this.editSP();
        }
    }//GEN-LAST:event_tblSanPhamMousePressed

    private void btnClearPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearPPActionPerformed
        // TODO add your handling code here:
        this.clearNPP();
    }//GEN-LAST:event_btnClearPPActionPerformed

    private void btnDelPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelPPActionPerformed
        // TODO add your handling code here:
        this.deleteNPP();
        this.clearNPP();
    }//GEN-LAST:event_btnDelPPActionPerformed

    private void btnUpdatePPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePPActionPerformed
        // TODO add your handling code here:
        this.updateNPP();
    }//GEN-LAST:event_btnUpdatePPActionPerformed

    private void btnThemPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemPPActionPerformed
        // TODO add your handling code here:
        this.insertNPP();
    }//GEN-LAST:event_btnThemPPActionPerformed

    private void btnLastPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastPPActionPerformed
        // TODO add your handling code here:
        this.LastNPP();
    }//GEN-LAST:event_btnLastPPActionPerformed

    private void btnNextPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPPActionPerformed
        // TODO add your handling code here:
        this.NextNPP();
    }//GEN-LAST:event_btnNextPPActionPerformed

    private void btnPrevPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevPPActionPerformed
        // TODO add your handling code here:
        this.PrevNPP();
    }//GEN-LAST:event_btnPrevPPActionPerformed

    private void btnFirstPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstPPActionPerformed
        // TODO add your handling code here:
        this.firstNPP();
    }//GEN-LAST:event_btnFirstPPActionPerformed

    private void btnFindPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindPPActionPerformed
        // TODO add your handling code here:
        this.fillTableNhaPP();
    }//GEN-LAST:event_btnFindPPActionPerformed

    private void lblHinhNPPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhNPPMouseClicked
        // TODO add your handling code here:
        this.selectImageNPP();
    }//GEN-LAST:event_lblHinhNPPMouseClicked

    private void tblNhaPhanPhoiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhaPhanPhoiMousePressed
        // TODO add your handling code here:
        this.row = tblNhaPhanPhoi.rowAtPoint(evt.getPoint());
        if (this.row >= 0) {
            this.editNPP();
        }
    }//GEN-LAST:event_tblNhaPhanPhoiMousePressed

    private void cboNhaPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNhaPPActionPerformed
        // TODO add your handling code here:
        try {
            String tennpp = (String) cboNhaPP.getSelectedItem();
            List<NhaPhanPhoi> list = daoNPP.select();
            for (NhaPhanPhoi npp : list) {
                if (tennpp.equalsIgnoreCase(npp.getTenNPP())) {
                    txtMaPP.setText(npp.getMaNPP());
                }
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_cboNhaPPActionPerformed

    private void mniGiamGiaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGiamGiaSPActionPerformed
        // TODO add your handling code here:
        int index = tblSanPham.getSelectedRow();
        long oldPrice;
        double giamgia;
        long newPrice;
        String discount = JOptionPane.showInputDialog(this, "Giảm giá theo %", "Giảm giá", JOptionPane.QUESTION_MESSAGE);
        giamgia = Double.parseDouble(discount) / 100;
        oldPrice = (long) tblSanPham.getValueAt(index, 5);
        newPrice = (long) (oldPrice - (oldPrice * giamgia));
        txtDonGiaSP.setText(newPrice + "");
        SanPham modelSP = getFormSP();
        try {
            daoSP.updateGia(modelSP);
            this.fillTableSP();
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
        }
    }//GEN-LAST:event_mniGiamGiaSPActionPerformed

    private void txtFindNPPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindNPPKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.fillTableNhaPP();
        }
    }//GEN-LAST:event_txtFindNPPKeyPressed

    private void txtFindSPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindSPKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.fillTableSP();
        }
    }//GEN-LAST:event_txtFindSPKeyPressed

    private void btnQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQRActionPerformed
        // TODO add your handling code here:
        if (tblSanPham.getSelectedRow() != -1) {
            writeQR();
            readQR();
        } else {
//            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm");
        }

    }//GEN-LAST:event_btnQRActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearPP;
    private javax.swing.JButton btnClearSP;
    private javax.swing.JButton btnDelPP;
    private javax.swing.JButton btnDelSP;
    private javax.swing.JButton btnFindPP;
    private javax.swing.JButton btnFindSP;
    private javax.swing.JButton btnFirstPP;
    private javax.swing.JButton btnFirstSP;
    private javax.swing.JButton btnLastPP;
    private javax.swing.JButton btnLastSP;
    private javax.swing.JButton btnNextPP;
    private javax.swing.JButton btnNextSP;
    private javax.swing.JButton btnPrevPP;
    private javax.swing.JButton btnPrevSP;
    private javax.swing.JButton btnQR;
    private javax.swing.JButton btnThemPP;
    private javax.swing.JButton btnThemSP;
    private javax.swing.JButton btnUpdatePP;
    private javax.swing.JButton btnUpdateSP;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboLoai;
    private javax.swing.JComboBox<String> cboNhaPP;
    private javax.swing.JFileChooser fileChooserNPP;
    private javax.swing.JFileChooser fileChooserSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblHinhNPP;
    private javax.swing.JLabel lblHinhSP;
    private javax.swing.JLabel lblQR;
    private javax.swing.JMenuItem mniGiamGiaSP;
    private javax.swing.JPanel pnlChucNangPP;
    private javax.swing.JRadioButton rdoConHang;
    private javax.swing.JRadioButton rdoHetHang;
    private javax.swing.JTextArea taMoTa;
    private javax.swing.JTable tblNhaPhanPhoi;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtDonGiaSP;
    private javax.swing.JTextField txtFindNPP;
    private javax.swing.JTextField txtFindSP;
    private javax.swing.JTextField txtMaNPP;
    private javax.swing.JTextField txtMaPP;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtNSXPP;
    private javax.swing.JTextField txtSoLuongSP;
    private javax.swing.JTextField txtTenNhaPP;
    private javax.swing.JTextField txtTenSP;
    // End of variables declaration//GEN-END:variables
    void fillTableNhaPP() {
        modelNPP = (DefaultTableModel) tblNhaPhanPhoi.getModel();
        modelNPP.setRowCount(0);
        try {
            String keyword = txtFindNPP.getText();
            listNPP = (ArrayList<NhaPhanPhoi>) daoNPP.selectByKeyword(keyword);
            for (NhaPhanPhoi npp : listNPP) {
                Object[] row = {
                    npp.getMaNPP(),
                    npp.getTenNPP(),
                    npp.getNoiSX(),
                    npp.getHinh()
                };
                modelNPP.addRow(row);
            }
            fillComBoBox();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void setForm(NhaPhanPhoi modelNPP) {
        txtMaNPP.setText(modelNPP.getMaNPP());
        txtTenNhaPP.setText(modelNPP.getTenNPP());
        txtNSXPP.setText(modelNPP.getNoiSX());
        lblHinhNPP.setText(modelNPP.getHinh());
        if (modelNPP.getHinh() != null) {
            Image img = XImage.readLogo(modelNPP.getHinh()).getImage().getScaledInstance(160, 180, Image.SCALE_SMOOTH);
            lblHinhNPP.setIcon(new ImageIcon(img));
        } else {
            lblHinhNPP.setIcon(null);
        }
    }

    NhaPhanPhoi getForm() {
        NhaPhanPhoi modelNPP = new NhaPhanPhoi();
        modelNPP.setMaNPP(txtMaNPP.getText());
        modelNPP.setTenNPP(txtTenNhaPP.getText());
        modelNPP.setNoiSX(txtNSXPP.getText());
        modelNPP.setHinh(lblHinhNPP.getToolTipText());
        return modelNPP;
    }

    void editNPP() {
        try {
            String MaNPP = (String) tblNhaPhanPhoi.getValueAt(this.row, 0);
            NhaPhanPhoi npp = daoNPP.findById(MaNPP);
            if (npp != null) {
                setForm(npp);
                updateStatusNPP();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    void insertNPP() {
        int flag = 0;
        if (valiNPP()) {
            NhaPhanPhoi modelNPP = getForm();
            for (NhaPhanPhoi npp : listNPP) {
                if (txtMaNPP.getText().equalsIgnoreCase(npp.getMaNPP())) {
                    JOptionPane.showMessageDialog(this, "Trùng mã, vui lòng nhập mã khác !");
                    flag = 1;
                }
            }
            if (flag != 1) {
                daoNPP.insert(modelNPP);
                this.fillTableNhaPP();
                JOptionPane.showMessageDialog(this, "Thêm mới thành công!");
            }
        }
    }

    void updateNPP() {
        NhaPhanPhoi modelNPP = getForm();
        if (valiNPP()) {
            try {
                daoNPP.update(modelNPP);
                this.fillTableNhaPP();
                JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
            }
        }
    }

    void deleteNPP() {
        int answer = JOptionPane.showConfirmDialog(this, "Bạn có thực sự muốn xóa nhà phân phối này ?", "Delete", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (answer == JOptionPane.YES_OPTION) {
            String manpp = txtMaNPP.getText();
            try {
                daoNPP.delete(manpp);
                this.fillTableNhaPP();
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Xóa thất bại!");
            }
        }
    }

    void clearNPP() {
        this.setForm(new NhaPhanPhoi());
        this.updateStatusNPP();
        row = -1;
        updateStatusNPP();
    }

    void selectImageNPP() {
        if (fileChooserNPP.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooserNPP.getSelectedFile();
            if (XImage.saveLogo(file)) {
                Image img = XImage.readLogo(file.getName()).getImage().getScaledInstance(lblHinhNPP.getWidth(), lblHinhNPP.getHeight(), Image.SCALE_SMOOTH);
                lblHinhNPP.setIcon(new ImageIcon(img));
                lblHinhNPP.setToolTipText(file.getName());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn ảnh");
        }

    }

    void firstNPP() {
        row = 0;
        tblNhaPhanPhoi.setRowSelectionInterval(row, row);
        editNPP();
    }

    void PrevNPP() {
        if (row > 0) {
            row--;
            tblNhaPhanPhoi.setRowSelectionInterval(row, row);
            editNPP();
        }
    }

    void NextNPP() {
        if (row < tblNhaPhanPhoi.getRowCount() - 1) {
            row++;
            tblNhaPhanPhoi.setRowSelectionInterval(row, row);
            editNPP();
        }
    }

    void LastNPP() {
        row = tblNhaPhanPhoi.getRowCount() - 1;
        tblNhaPhanPhoi.setRowSelectionInterval(row, row);
        editNPP();
    }

    void updateStatusNPP() {
        boolean edit = this.row >= 0;
        boolean first = this.row == 0;
        boolean last = this.row == tblNhaPhanPhoi.getRowCount() - 1;
        txtMaNPP.setEditable(!edit);
        btnThemPP.setEnabled(!edit);
        btnUpdatePP.setEnabled(edit);
        btnDelPP.setEnabled(edit);
        btnFirstPP.setEnabled(edit && !first);
        btnPrevPP.setEnabled(edit && !first);
        btnNextPP.setEnabled(edit && !last);
        btnLastPP.setEnabled(edit && !last);
    }

    public boolean valiNPP() {
        if (txtMaNPP.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Không được để trống mã nhà phân phối !");
            txtMaNPP.requestFocus();
            return false;
        }
        if (txtTenNhaPP.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Không được để trống tên nhà phân phối !");
            txtTenNhaPP.requestFocus();
            return false;
        }
        if (txtNSXPP.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Không được để trống nơi sản xuất !");
            txtNSXPP.requestFocus();
            return false;
        }
        return true;
    }

//    public void getFirsttableNPP(){
//        modelNPP = (DefaultTableModel) tblNhaPhanPhoi.getModel();
//        tblNhaPhanPhoi.setRowSelectionInterval(0, 0);
//        int index = tblNhaPhanPhoi.getSelectedRow();
//        txtMaNPP.setText((String)tblNhaPhanPhoi.getValueAt(0, 0));
//        txtTenNhaPP.setText((String)tblNhaPhanPhoi.getValueAt(0, 1));
//        txtNSXPP.setText((String)tblNhaPhanPhoi.getValueAt(0, 2));
//        String hinh = (String) tblNhaPhanPhoi.getValueAt(0, 3);
//        lblHinhNPP.setText(hinh);
//        if (hinh != null) {
//            Image imgSP = XImage.readLogo(hinh).getImage().getScaledInstance(150, 180, Image.SCALE_SMOOTH);
//            lblHinhNPP.setIcon(new ImageIcon(imgSP));
//        }
//    }
    void fillTableSP() {
        modelSP = (DefaultTableModel) tblSanPham.getModel();
        modelSP.setRowCount(0);
        try {
            String keyword = txtFindSP.getText();
            listSP = (ArrayList<SanPham>) daoSP.selectByKeyword(keyword);
            for (SanPham sp : listSP) {
                Object[] row = {
                    sp.getMaSP(),
                    sp.getTenSP(),
                    sp.getMaNPP(),
                    sp.getTenNPP(),
                    sp.getSoLuong(),
                    sp.getDonGia(),
                    sp.getLoai(),
                    sp.getMoTa(),
                    sp.getHinh(),
                    sp.isTinhTrang() ? "Còn hàng" : "Hết hàng"
                };
                modelSP.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Đổ dữ liệu thất bại");
        }
    }

    void setFormSP(SanPham modelSP) {
        txtMaSP.setText(modelSP.getMaSP());
        txtTenSP.setText(modelSP.getTenSP());
        NhaPhanPhoi npp = daoNPP.findById(modelSP.getMaNPP());
        cboNhaPP.setSelectedItem(npp.getTenNPP());
        txtMaPP.setText(npp.getMaNPP());
        txtSoLuongSP.setText(modelSP.getSoLuong() + "");
        txtDonGiaSP.setText(modelSP.getDonGia() + "");
        cboLoai.setSelectedItem(modelSP.getLoai());
        taMoTa.setText(modelSP.getMoTa());
        rdoConHang.setSelected(modelSP.isTinhTrang());
        rdoHetHang.setSelected(!modelSP.isTinhTrang());
        lblHinhSP.setText(modelSP.getHinh());
        if (modelSP.getHinh() != null) {
            Image imgSP = XImage.readLogo(modelSP.getHinh()).getImage().getScaledInstance(170, 180, Image.SCALE_SMOOTH);
            lblHinhSP.setIcon(new ImageIcon(imgSP));
        } else {
            lblHinhSP.setIcon(null);
        }
    }

    SanPham getFormSP() {
        SanPham modelSP = new SanPham();
        modelSP.setMaSP(txtMaSP.getText());
        modelSP.setTenSP(txtTenSP.getText());
        modelSP.setTenNPP(cboNhaPP.getSelectedItem() + "");
        modelSP.setMaNPP(txtMaPP.getText());
        modelSP.setSoLuong(Integer.parseInt(txtSoLuongSP.getText()));
        modelSP.setDonGia(Long.parseLong(txtDonGiaSP.getText()));
        modelSP.setLoai(cboLoai.getSelectedItem() + "");
        modelSP.setMoTa(taMoTa.getText());
        modelSP.setHinh(lblHinhSP.getToolTipText());
        modelSP.setTinhTrang(rdoConHang.isSelected());
        return modelSP;
    }

    void editSP() {
        try {
            String MaSP = (String) tblSanPham.getValueAt(this.row, 0);
            SanPham sp = daoSP.findById(MaSP);
            if (sp != null) {
                setFormSP(sp);
                updateStatusSP();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    void insertSP() {
        int flag = 0;
        if (valiSP()) {
            SanPham modelSP = getFormSP();
            for (SanPham sanPham : listSP) {
                if (txtMaSP.getText().equalsIgnoreCase(sanPham.getMaSP())) {
                    JOptionPane.showMessageDialog(this, "Trùng mã, vui lòng nhập mã khác !");
                    flag = 1;
                }
            }
            if (flag != 1) {
                daoSP.insert(modelSP);
                this.fillTableSP();
                JOptionPane.showMessageDialog(this, "Thêm thành công !");
            }
        }
    }

    void updateSP() {
        SanPham modelSP = getFormSP();
        if (valiSP()) {
            try {
                daoSP.update(modelSP);
                this.fillTableSP();
                JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
            }
        }
    }

    void deleteSP() {
        int answer = JOptionPane.showConfirmDialog(this, "Bạn có thực sự muốn xóa sản phẩm này ?", "Delete", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (answer == JOptionPane.YES_OPTION) {
            String masp = txtMaSP.getText();
            try {
                daoSP.delete(masp);
                this.fillTableSP();
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Xóa thất bại!");
            }
        }
    }

    void clearSP() {
        txtMaSP.setText("");
        txtTenSP.setText("");
        cboNhaPP.setSelectedIndex(0);
        txtSoLuongSP.setText("0");
        txtDonGiaSP.setText("0");
        cboLoai.setSelectedIndex(0);
        buttonGroup1.clearSelection();
        lblHinhSP.setIcon(null);
        lblHinhSP.setText(null);
        taMoTa.setText("");
        this.updateStatusSP();
        row = - 1;
        updateStatusSP();
    }

    void selectImageSP() {
        if (fileChooserNPP.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooserNPP.getSelectedFile();
            if (XImage.saveLogo(file)) {
                Image imgSP = XImage.readLogo(file.getName()).getImage().getScaledInstance(lblHinhSP.getWidth(), lblHinhSP.getHeight(), Image.SCALE_SMOOTH);
                lblHinhSP.setIcon(new ImageIcon(imgSP));
                lblHinhSP.setToolTipText(file.getName());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn ảnh");
        }
    }

    void firstSP() {
        row = 0;
        tblSanPham.setRowSelectionInterval(row, row);
        editSP();
    }

    void PrevSP() {
        if (row > 0) {
            row--;
            tblSanPham.setRowSelectionInterval(row, row);
            editSP();
        }
    }

    void NextSP() {
        if (row < tblSanPham.getRowCount() - 1) {
            row++;
            tblSanPham.setRowSelectionInterval(row, row);
            editSP();
        }
    }

    void LastSP() {
        row = tblSanPham.getRowCount() - 1;
        tblSanPham.setRowSelectionInterval(row, row);
        editSP();
    }

    void updateStatusSP() {
        boolean edit = this.row >= 0;
        boolean first = this.row == 0;
        boolean last = this.row == tblSanPham.getRowCount() - 1;
        txtMaSP.setEditable(!edit);
        btnThemSP.setEnabled(!edit);
        rdoHetHang.setEnabled(edit);
        btnUpdateSP.setEnabled(edit);
        btnDelSP.setEnabled(edit);
        btnQR.setEnabled(edit);
        btnFirstSP.setEnabled(edit && !first);
        btnPrevSP.setEnabled(edit && !first);
        btnNextSP.setEnabled(edit && !last);
        btnLastSP.setEnabled(edit && !last);
    }

    public boolean valiSP() {
        if (txtMaSP.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Không được để trống mã sản phẩm !");
            txtMaSP.requestFocus();
            return false;
        }
        if (txtTenSP.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Không được để trống tên sản phẩm !");
            txtTenSP.requestFocus();
            return false;
        }
        if (txtSoLuongSP.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Không được để trống số lượng !");
            txtSoLuongSP.requestFocus();
            return false;
        }
        try {
            int soluong = Integer.parseInt(txtSoLuongSP.getText());
            if (soluong <= 0) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng lớn hơn 0 !");
                return false;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Số lượng vui lòng nhập số !");
            return false;
        }
        if (txtDonGiaSP.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Không được để trống đơn giá !");
            txtDonGiaSP.requestFocus();
            return false;
        }
        try {
            double dongia = Double.parseDouble(txtDonGiaSP.getText());
            if (dongia <= 0) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đơn giá lớn hơn 0 !");
                return false;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Đơn giá vui lòng nhập số !");
            return false;
        }
        if (cboLoai.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn loại hàng !");
            return false;
        }
        if (rdoConHang.isSelected() == false && rdoHetHang.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn tình trạng hàng !");
            return false;
        }
        return true;
    }

    void fillComBoBox() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboNhaPP.getModel();
        model.removeAllElements();
        try {
            List<NhaPhanPhoi> list = daoNPP.select();
            for (NhaPhanPhoi npp : list) {
                model.addElement(npp.getTenNPP());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không fill lên được ComboBox");;
        }
    }

    void writeQR() {
        try {
            ByteArrayOutputStream out = QRCode.from("Produtct ID: " + txtMaSP.getText()
                    + "\n" + "Product Name: " + txtTenSP.getText()
                    + "\n" + "Cost: " + txtDonGiaSP.getText()).to(ImageType.PNG).stream();
            String f_name = txtMaSP.getText();
            String path_name = "E:\\CuaHangLapTop\\DuAn1\\";
            FileOutputStream fos = new FileOutputStream(new File(path_name + (f_name + ".PNG")));
            fos.write(out.toByteArray());
            fos.flush();
        } catch (Exception e) {
            System.out.println("" + e);
        }
    }

    void readQR() {
        try {
            InputStream barcodeInputStream = new FileInputStream("E:\\CuaHangLapTop\\DuAn1\\" + txtMaSP.getText().trim() + ".PNG");
            BufferedImage barcBufferedImage = ImageIO.read(barcodeInputStream);
            LuminanceSource source = new BufferedImageLuminanceSource(barcBufferedImage);
            BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));
            Reader reader = new MultiFormatReader();
            Result result = reader.decode(bitmap);
            ImageIcon img = new ImageIcon("E:\\CuaHangLapTop\\DuAn1\\" + txtMaSP.getText().trim() + ".PNG");
            lblQR.setIcon(img);
            JOptionPane.showMessageDialog(this, img, "QR", -1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm");
        }
    }
}
